services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: YOUR_DB_USERNAME
      APP_USER_PASSWORD: YOUR_DB_PASSWORD
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus -S airflow/airflow@localhost/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 10
